In [1]:
# What is the numpy array
# it's like a data in any dimension of array

#  how the numpy differ with the lists
# list is slow while the numpy is fast

# Why numpy is faster?
# faster to read less bytes of memory
# no type checking while moving through object
# contiguoous memory

# How are list different from numpy?

# Application of numpy
# Matlab replacement
# matplotlib
# backened
# Machine learning 


In [2]:
import numpy as np

# the basics

In [3]:
a = np.array([1,2,3],dtype = 'int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,4],[3,4,5]])
print(b)

[[9. 8. 4.]
 [3. 4. 5.]]


In [5]:
# Get dimensions

a.ndim

1

In [6]:
# Get shape
b.shape

(2, 3)

In [7]:
# Get data type
a.dtype

dtype('int16')

In [8]:
# Get size
a.itemsize

2

In [9]:
# Get total size
a.nbytes

6

# Accessing/Changing specific elements,rows columns,etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# get a specific element 
a[1,-1]

14

In [14]:
# Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific columns
a[:,2]

array([ 3, 10])

In [21]:
#Getting a little more fancy[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [22]:
a[1,5]= 20

In [23]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
a[:,2] = [1,2]

In [25]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [28]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
#Get specifec element
b[:,1,1]

array([4, 8])

# initializing different type of array

In [32]:
# All zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# All ones matrix
np.ones((4,2,2),dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [34]:
# Any other matrix
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [37]:
# Any other number (Full like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [38]:
# Aandom decimal numbers
np.random.rand(4,2)

array([[0.37762177, 0.80453078],
       [0.1088407 , 0.33228045],
       [0.74190942, 0.26523078],
       [0.97077248, 0.81847031]])

In [40]:
np.random.random_sample(a.shape)

array([[0.64883237, 0.68855348, 0.46302921, 0.53366982, 0.662019  ,
        0.80963843, 0.67245614],
       [0.44278374, 0.84871004, 0.52576717, 0.11553583, 0.49439665,
        0.58530554, 0.32520514]])

In [42]:
# Random Integer value
np.random.randint(3,45,size=((2,3)))

array([[33, 33, 34],
       [18,  3,  5]])

In [45]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis =0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
output = np.ones([5,5])
print(output)
z =np.zeros((3,3))
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [63]:
a = np.array([1,2,3])
b = a
c = a.copy()
c[0] = 10
print(a)
print(b)

[1 2 3]
[1 2 3]


# Mathematics

In [64]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [65]:
a+2

array([3, 4, 5, 6])

In [66]:
a-2

array([-1,  0,  1,  2])

In [67]:
a*2

array([2, 4, 6, 8])

In [68]:
a+= 3

In [69]:
a

array([4, 5, 6, 7])

In [70]:
b = a.copy()
b+a

array([ 8, 10, 12, 14])

In [71]:
a**3

array([ 64, 125, 216, 343], dtype=int32)

In [72]:
#Take the sin
np.sin(a)

array([-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ])

In [73]:
np.tan(a)

array([ 1.15782128, -3.38051501, -0.29100619,  0.87144798])

#### linear algebra

In [81]:
a = np.full((2,3),1)
print(a)
b = np.full((3,4),3)
print(b)

np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


array([[9, 9, 9, 9],
       [9, 9, 9, 9]])

In [82]:
c = np.identity(3)

In [84]:
# fint the determinants of matrix
np.linalg.det(c)

1.0

#### Statistics

In [86]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.min(stats)

1

In [88]:
np.max(stats,axis = 1)

array([3, 6])

In [89]:
np.sum(stats,axis = 0)

array([5, 7, 9])

#### Reorganizing arrays

In [93]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [96]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2,v1,v2]))
print(np.hstack([v1,v2,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8 5 6 7 8 1 2 3 4]


#### Miscleaneous

### load data from file

In [102]:
file_data = np.genfromtxt('data.txt',delimiter=',')
file_data.astype('int32')
file_data

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

###### Advanced indexing

In [105]:
file_data[file_data>3]

array([4., 5., 6., 7., 8., 9.])

In [ ]:
# you can index with a list in a numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[]